name: 'MongoDB Action'
description: 'Start a MongoDB server'

branding:
  icon: 'database'
  color: 'green'

inputs:
  network:
    description: 'Docker network to use (default "bridge")'
    required: false
    default: 'bridge'

  version:
    description: 'MongoDB version to use (default "latest")'
    required: false
    default: 'latest'

  host:
    description: 'MongoDB version to use (default "mongo")'
    required: false
    default: 'mongo'

  port:
    description: 'MongoDB port to use (default 27017)'
    required: false
    default: '27017'

  username:
    description: 'MongoDB root username (default: none)'
    required: false
    default: ''

  password:
    description: 'MongoDB root password (default: none)'
    required: false
    default: ''

  database:
    description: 'MongoDB db to create (default: none)'
    required: false
    default: ''

  replica_set:
    description: 'MongoDB replica set name (no replica set by default)'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.network }}
    - ${{ inputs.version }}
    - ${{ inputs.host }}
    - ${{ inputs.port }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.database }}
    - ${{ inputs.replica_set }}