name: Test
on: [push, pull_request]
env:
  MONGO_DATABASE: miragedb
  MONGO_USERNAME: miragedb
  MONGO_PASSWORD: miragedb
  MONGO_REPLICA_SET: rs0
jobs:
  test:
    name: Test
    container: 
      image: docker://ubuntu:latest
      ports:
        - 27017
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version: [16]
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start MongoDB Server
      uses: ./
      with:
        username: ${{ env.MONGO_USERNAME }}
        password: ${{ env.MONGO_PASSWORD }}
        database: ${{ env.MONGO_DATABASE }}
        replica_set: ${{ env.MONGO_REPLICA_SET }}
    - name: Install dependencies
      run: npm install --global yarn && yarn install
    - name: Run tests
      run: yarn jest --roots ./test
